export let state = {
  id: "",
  showCountItems: false,
  isEnter: false,
  totalItems: 0,
  btnSearch: false,
  cardClick: false,
  cardActive: false,
  inputValue: "",
  valueOfCategory: "all",
  valueOfNovelty: "relevance",
  startIndex: 0,
  maxShowResults: 10,
  isLoading: false,
  dataItems: [],
  isError: false,
  baseUrl: "https://www.googleapis.com/books/v1/volumes?",
  detailedCard:null,
};